name: "Blog-App"
services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - blog-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - blog-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass "root"
    depends_on:
      - mongo-db
  
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - blog-network
    depends_on:
      - mongo-db
      - redis
    env_file:
      - ./backend/.env
  
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "5173:5173"
    networks:
      - blog-network
    depends_on:
      - backend
      - mongo-db
      - redis
    env_file:
      - ./frontend/.env


volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local

networks:
  blog-network:
    driver: bridge
    
