version: "3.8"
services:
  mongo-db:
    image: mongo:latest
    container_name: mongo-db
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    networks:
      - blog-network
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - '6379:6379'
    networks:
      - blog-network
    volumes:
      - redis-data:/data
    command: redis-server --appendonly yes --requirepass "root"
    depends_on:
      - mongo-db
  backend:
    image: aryan314/backend-blog:401b9001691e7f7baaed1765ca0fe05c5d412f4b
    container_name: backend
    ports:
      - '8080:8080'
    networks:
      - blog-network
    depends_on:
      - mongo-db
      - redis
    env_file:
      - ./.env
  frontend:
    image: aryan314/frontend-blog:82fcf2ba1708a3dfda73d792071abb2bb2d72c85
    container_name: frontend
    ports:
      - '5173:5173'
    networks:
      - blog-network
    depends_on:
      - backend
      - mongo-db
      - redis
volumes:
  mongo-data:
    driver: local
  redis-data:
    driver: local
networks:
  blog-network:
    driver: bridge
